<html>
    <head>
        <title>BIODATA PHP</title>

<style>
    body {

        background-image: url("abstract.jpeg"),url("images.jpeg");
        background-color: #cccccc;
    }
 

</style>

 </head>

 <body>

      <?php
      echo"<center><table border = 1 cellspacing = 3 width = 750 bgcolor =white>
          <tr><th colspan = 3>BIODATA MAHASISWA</th><tr>
          <tr><td>NIM</td><td>17220612</td></tr>
          <tr><td>Nama</td><td>PRASETYO BAYU AJI</td></tr>
          <tr><td>Program Studi</td><td>Teknologi Informasi</td></tr>
          <tr><td>Kelas</td><td>17.3A.25</td></tr>
          <tr><td>Kampus</td><td>UBSI Cengkareng</td></tr>
          </center></table>";
     
    
      ?>
      <br>
      <a href="biodata2.PHP">==========> Klik Halaman Data Nilai <==========</a>
</body>
</html>
            
        
      









     

      
   
   
  






    



